### PR TITLE
Read Kubeconfig from env var if previous methods don't work

### LINKED ISSUE #99: Support reading KubeConfig from KUBECONFIG env var
We don't currently support reading KubeConfig from `KUBECONFIG` env var and because of that the OLM scorecard tests fail. See https://github.com/operator-framework/community-operators/pull/1192

We support passing the masterUrl and kubeconfig as command line arguments only.

BTW, I think we need to skip having 0.12 on OperatorHub because we wouldn't make a new release only for this ticket.

I closed the ticket at Operator Hub https://github.com/operator-framework/community-operators/pull/1192

### PR DESCRIPTION
**Pull request by aliok**
# Issue to be fixed

Fixes #99 

## Proposed Changes

* Backwards compatible change
* Only use `KUBECONFIG` if the command line argument is empty

## Release Note

```release-note
NONE
```

Why having this fixes the tests at Operator Hub?
Operator Hub tests work like this:
- Operator is installed on Minikube
- A proxy side car is installed with the operator
- That proxy side car would be the proxy for Kube API and the operator would talk to Kube API through that
- Proxy injects the kubeconfig to the operator container with an env var called `KUBECONFIG`
- Tests then check if the operator reacts to creation of CRs

In our case, operator was doing its work good, but was not using the proxy and thus the tests were unable to detect the operator's actions.

### CODE REVIEW

**Comment by aliok** [comment]
This change fixes the Operator Hub checks. See https://github.com/operator-framework/community-operators/pull/1218 for verification.

File: pkg/reconciler/knativeeventing/controller.go [hunk 1]
```diff
@@ -59,7 +59,12 @@ func NewController(
 
 	koDataDir := os.Getenv("KO_DATA_PATH")
 
-	cfg, err := clientcmd.BuildConfigFromFlags(*MasterURL, *Kubeconfig)
+	KubeconfigToUse := *Kubeconfig
```
Comment (houshengbo) [inline pkg/reconciler/knativeeventing/controller.go]: What about we remove all the changes, but replace
```
Kubeconfig = flag.String("kubeconfig", "", "Path to a kubeconfig. Only required if out-of-cluster.")
```

with 

```
Kubeconfig = flag.String("kubeconfig", os.Getenv("KUBECONFIG"), "Path to a kubeconfig. Only required if out-of-cluster.") along Line 42 in  pkg/reconciler/knativeeventing/controller.go?
```????

File: cmd/manager/main.go [hunk 2]
```diff
@@ -28,7 +29,13 @@ import (
 func main() {
 	flag.Parse()
 
-	cfg, err := clientcmd.BuildConfigFromFlags(*knativeeventing.MasterURL, *knativeeventing.Kubeconfig)
+	Kubeconfig := *knativeeventing.Kubeconfig
```
Comment (houshengbo) [inline cmd/manager/main.go]: What about we remove all the changes, but replace
```
Kubeconfig = flag.String("kubeconfig", "", "Path to a kubeconfig. Only required if out-of-cluster.")
```

with 

```
Kubeconfig = flag.String("kubeconfig", os.Getenv("KUBECONFIG"), "Path to a kubeconfig. Only required if out-of-cluster.") along Line 42 in  pkg/reconciler/knativeeventing/controller.go?
```
????

File: pkg/reconciler/knativeeventing/controller.go (hunk 1 above)
Comment (aliok) [reply pkg/reconciler/knativeeventing/controller.go]: Good point :D

**Comment by aliok** [comment]
@houshengbo Changed as per your suggestion. It is a better way. Thanks a lot!
