### PR TITLE
Keep the sources-controller, since 0.12 still has it

### LINKED ISSUE #116: sources-controller is available in 0.12, but it is removed by the reconcile loop
**Describe the bug**
This is my mistake by adding the controller removal in 0.12, it should happen in 13.

**Expected behavior**
sources-controller is still kept in 0.12.

**To Reproduce**
Download the branch of release-0.12, and run from source code to install eventing.

**Knative release version**
0.12

**Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by houshengbo**
# Issue to be fixed

Fixes #116

## Proposed Changes

* This PR fixes an overlooked error in 0.12, which is that 0.12 still has the deployment named sources-controller.

## Release Note

```release-note
```

### CODE REVIEW

File: pkg/reconciler/knativeeventing/knativeeventing.go [hunk 1]
```diff
@@ -209,50 +207,3 @@ func (r *Reconciler) updateStatus(desired *eventingv1alpha1.KnativeEventing) (*e
 	existing.Status = desired.Status
 	return r.KnativeEventingClientSet.OperatorV1alpha1().KnativeEventings(desired.Namespace).UpdateStatus(existing)
 }
-
-// Delete obsolete resources from previous versions
```
Comment (k4leung4) [inline pkg/reconciler/knativeeventing/knativeeventing.go]: why are these changes in here?

Comment (houshengbo) [reply pkg/reconciler/knativeeventing/knativeeventing.go]: @k4leung4 This function is used to delete the old resources in the old version. However, this is a fix for the old version 0.12, so I should not have added the resource deletion.

File: test/e2e-upgrade-tests.sh [hunk 2]
```diff
@@ -93,6 +93,11 @@ function generate_latest_eventing_manifest() {
   # Download the source code of knative eventing
   git clone https://github.com/knative/eventing.git
   cd eventing
+  if [[ ! -z "$1" ]]; then
```
Comment (k4leung4) [inline test/e2e-upgrade-tests.sh]: can we add comment above the function to explain that it takes in a parameter, and what the parameter is.

Comment (houshengbo) [reply test/e2e-upgrade-tests.sh]: sure.
